config/routes.rb
Rails.application.routes.draw do
  resources :lottery_tables do
    resources :lotteries
  end

  root 'lottery_tables#index', as: 'lottery_tables_index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lotteries_builder.rb
class LotteriesBuilder
  include ActiveModel::Model

  attr_accessor :lottery_table
  attr_accessor :lotteries
  attr_accessor :rate

  validates :rate, presence: true,
                   length: { in: 1..5 }

  def initialize(attribute = nil)
    @lottery_table = attribute
    @lotteries = []
  end

  def new(attributes = {})
    @rate = attributes[:rate]
    amount = attributes[:amount].to_i

    @rate.strip!
    @rate.upcase!

    amount.times do
      @lotteries << lottery_table.lotteries.new(rate: @rate)
    end
  end

  def save
    return false unless valid?
    @lotteries.map(&:save)
  end
end

app/models/lottery.rb
class Lottery < ApplicationRecord
  belongs_to :lottery_table

  before_validation :rate_uppercase

  validates :rate, presence: true,
                   length: { in: 1..5 }

  private

  def rate_uppercase
    rate.strip!
    rate.upcase!
  end
end

app/models/lottery_table.rb
class LotteryTable < ApplicationRecord

  attr_accessor :lotteries_builder

  has_many :lotteries, dependent: :destroy

  after_initialize :set_lotteries_builder
  # after_find :set_lotteries_builder

  validates :title, presence: true

  private

  def set_lotteries_builder
    @lotteries_builder = LotteriesBuilder.new(self)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lotteries_controller.rb
class LotteriesController < ApplicationController
  before_action :set_lottery_table

  def index
    @lotteries = @lottery_table.lotteries.all
  end

  def new
    @lottery = @lottery_table.lotteries.new
  end

  def create
    @lottery_table.lotteries_builder.new(lottery_params)

    respond_to do |format|
      if @lottery_table.lotteries_builder.save
        format.html { redirect_to lottery_table_lotteries_path, notice: 'Lottery was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def lottery_params
    params.require(:lottery).permit(:rate, :amount)
  end

  def set_lottery_table
    @lottery_table = LotteryTable.find(params[:lottery_table_id])
  end
end

app/controllers/lottery_tables_controller.rb
class LotteryTablesController < ApplicationController
  def index
    @lottery_tables = LotteryTable.all
  end

  def new
    @lottery_table = LotteryTable.new
  end

  def create
    @lottery_table = LotteryTable.new(lottery_table_params)

    respond_to do |format|
      if @lottery_table.save
        format.html { redirect_to lottery_tables_index_url, notice: 'LotteryTable was successfully created.' }
        format.json { render :show, status: :created, location: @lottery_table }
      else
        format.html { render :new }
        format.json { render json: @lottery_table.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def lottery_table_params
    params.require(:lottery_table).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kuji</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lotteries/index.html.erb
<h2>獎券列表</h2>

<div>
  <% if @lotteries.presence %>
    <table>
      <thead>
        <tr>
          <th>標題</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @lotteries.each do |lottery| %>
          <tr>
            <td><%= lottery.id %></td>
            <td><%= lottery.rate %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h3>尚未有獎券</h3>
  <% end %>
</div>

<div>
  <%= link_to '建立新獎券', new_lottery_table_lottery_path %>
</div>

app/views/lotteries/new.html.erb
<h2>新增</h2>

<%= form_with(model: Lottery.new,
              url: lottery_table_lotteries_path(@lottery_table),
              local: true) do |form| %>

  <div class="field">
    <%= form.label :rate %>
    <%= form.text_area :rate, id: :lottery_rate %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :lottery_amount, min: 1, step: 1, value: 1 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lottery_tables/index.html.erb
<h2>一番賞列表</h2>

<div>
  <% if @lottery_tables.presence %>
    <table>
      <thead>
        <tr>
          <th>標題</th>
        </tr>
      </thead>
      <tbody>
        <% @lottery_tables.each do |table| %>
          <tr>
            <td><%= link_to table.title, lottery_table_lotteries_path(table) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h3>尚未有抽獎</h3>
  <% end %>
</div>

<div>
  <%= link_to '建立新獎單', new_lottery_table_path %>
</div>

app/views/lottery_tables/new.html.erb
<h2>新增</h2>

<%#= render 'form', lottery_table: @lottery_table %>

<%= form_with(model: @lottery_table) do |form| %>
  <% if @lottery_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lottery_table.errors.count, "error") %> prohibited this @lottery_table from being saved:</h2>

      <ul>
      <% @lottery_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :lottery_table_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>